import styles from './Bases.module.scss';

const Bases = () => {
    
    return(
        <div className={styles.mainBasesContainer}>
            {/* <img src='assets/images/bases-background.jpg'/> */}
            <h1>Bases y Condiciones del "Sorteo 10 años de Mundo Risas"</h1>
            <p>1. Podrán participar del siguiente sorteo (en adelante “PROMOCIÒN”) organizado por MUNDO RISAS (en adelante “EL ORGANIZADOR o LA EMPRESA”) todas las personas que cumplan los siguientes requisitos:
                <br/>
                - Deberán ser (i) personas físicas, (ii) mayores de 18 años, (iii) residentes argentinos.
                <br/>
                - No podrán participar en la PROMOCIÓN empleados de la EMPRESA, ni de cualquiera de sus vinculadas, controlantes, controladas o asociadas, sea en forma directa o indirecta a través de terceras personas.
            </p>
            <p>2. La PROMOCIÓN se aplica exclusivamente en el territorio de la República Argentina.</p>
            <p>3. Procedimiento para validar la PROMOCIÓN: El participante que deberá cumplir con los requisitos establecidos en el punto 1 de la presente. La sola participación en la PROMOCIÓN implica para los participantes el conocimiento y la aceptación de las disposiciones previstas en los presentes Términos y Condiciones (en adelante “LAS BASES”), de conformidad con las disposiciones legales aplicables.
            </p>
            <p>4. Exclusión de responsabilidad; Indemnidad: Como condición para participar en la PROMOCIÓN, cada participante acepta que la EMPRESA no será responsable por ningún daño directo ni indirecto que pudiera sufrir el participante o cualquier tercero con motivo y/u ocasión de la participación en la PROMOCIÓN, y/o el uso, destino o finalidad del premio, renunciando la EMPRESA a cualquier tipo de responsabilidad contractual y/o extracontractual frente a los participantes y cualquier tercero, lo que es aceptado incondicionalmente por cada participante.</p>
            <p>5. Modificación a los “LAS BASES”: La EMPRESA podrá modificar cualquiera de los puntos enunciados en “LAS BASES”, siempre que no se altere la esencia de la PROMOCIÓN, por circunstancias imprevistas no imputables a esta. El mismo hecho de inscribirse en la PROMOCIÓN implica el conocimiento y la aceptación plena de los “LAS BASES”. Las decisiones de la EMPRESA sobre todos y cada uno de los aspectos de la PROMOCIÓN, incluyendo decisiones por cualquier cuestión no prevista en “LAS BASES” serán definitivas e irrecurribles. La EMPRESA se reserva el derecho de finalizar o modificar la PROMOCIÓN en caso de existir fraudes, dificultades técnicas o cualquier otro factor fuera del control de la EMPRESA que pudiera comprometer la integridad de la PROMOCIÓN. El Organizador se reserva el derecho de interpretar las presentes Bases, circunstancia que los Participantes aceptan por el solo hecho de participar en el Sorteo.</p>
            <p>6. PREMIO. - El Premio consiste en un evento de dos horas y media de duración para 30 niños y 20 adultos. El mismo evento se realizará de lunes a jueves, sujeto a disponibilidad horaria y previa reserva del espacio El Premio no incluye ningún otro concepto, bienes o servicios distintos o adicionales al enunciado específicamente. El Premio es intransferible, y no podrá exigirse su canje por dinero o por cualquier otro elemento. El Organizador podrá modificar el Premio por otro de la misma especie, de igual o mayor valor.</p>
            <p>7. VALIDEZ DEL PREMIO. - El Premio tendrá una validez de un año desde el día del sorteo (1ero octubre 2023). El Organizador no se hará cargo de ningún gasto de traslado del Ganador desde y hacia el lugar de entrega del premio (Pueyrredón 2136, Villa Ballester).  El Organizador se pondrá en contacto con el ganador para avisarle que salió beneficiado. Cualquier costo y/o gasto en que los Participantes deban incurrir para participar de la Promoción y/o para hacerse acreedores del Premio será a su exclusiva cuenta.</p>
            <p>8. RESPONSABILIDAD DEL ORGANIZADOR LUEGO DE LA ENTREGA DEL PREMIO. - El Organizador no responderá por ningún daño o perjuicio que se ocasione a cualquier persona con motivo o debido a la participación de la misma en la Promoción, en cualquier calidad que la misma participe, así como a cualquier reclamo o daño relacionado con cualquier aspecto de la misma, o incluyendo pero sin limitación, aquellos daños vinculados con el acceso y otorgamiento de cualquiera de los Premios, siempre que dicho daño no sea imputable a la exclusiva culpa grave o exclusivo dolo del Organizador. El Organizador no será responsable por daños, perjuicios o pérdidas ocasionados al Ganador o a cualquier otro tercero, en su persona y/o bienes, con motivo o en ocasión de la aceptación, recepción o utilización del Premio. El Organizador no otorga garantía de calidad, evicción, vicios redhibitorios, títulos perfectos, funcionamiento, ni ninguna otra garantía en relación con el Premio, debiendo dirigirse cualquier reclamo a los respectivos prestadores. El Organizador no será responsable por ningún daño o perjuicio, de cualquier tipo que fuere, que pudieren sufrir el Ganador o terceros, con motivo de o en relación con el uso del Premio. El Participante se abstiene de efectuar cualquier tipo de reclamo contra el Organizador por cualquier causa vinculada a la calidad, comercialización, garantías del producto/servicio de que se trate.</p>
            <p>9. En virtud de la normativa aplicable, se informa a los Participantes lo siguiente:
                [Ley 25.326, artículo 27:] “1. En la recopilación de domicilios, reparto de documentos, publicidad o venta directa y otras actividades análogas, se podrán tratar datos que sean aptos para establecer perfiles determinados con fines promocionales, comerciales o publicitarios; o permitan establecer hábitos de consumo, cuando éstos figuren en documentos accesibles al público o hayan sido facilitados por los propios titulares u obtenidos con su consentimiento. 8. En los supuestos contemplados en el presente artículo, el titular de los datos podrá ejercer el derecho de acceso sin cargo alguno. 3. El titular podrá en cualquier momento solicitar el retiro o bloqueo de su nombre de los bancos de datos a los que se refiere el presente artículo”.
                [Decreto 1558/2001, artículo 27, tercer párrafo:] “En toda comunicación con fines de publicidad que se realice por correo, teléfono, correo electrónico, Internet u otro medio a distancia a conocer, se deberá indicar, en forma expresa y destacada, la posibilidad del titular del dato de solicitar el retiro o bloqueo, total o parcial, de su nombre de la base de datos. A pedido del interesado, se deberá informar el nombre del responsable o usuario del banco de datos que proveyó la información”.
                [Disposición 10/2009, Dirección Nacional de Protección de Datos Personales:] “El titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley Nº 25.326”. “La DIRECCION NACIONAL DE PROTECCION DE DATOS PERSONALES, Órgano de Control de la Ley Nº 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales”.
            </p>
            <p>10. El Organizador no se responsabiliza por el uso que pueda hacerse de la información personal provista por cada PARTICIPANTE en el supuesto que sea utilizada sin su autorización o resultare de un hecho ilícito o en exceso de atribuciones de sus dependientes.</p>
            <p>11. Los Participantes ganadores otorgan al Organizador una autorización para publicar sus nombres, DNI y/o fotos, en los medios y en las formas de comunicación que el Organizador crea conveniente. Dicha autorización se otorga en forma incondicionada e irrevocable por el término de 2 (dos) años a contabilizarse desde la fecha de inicio del Plazo de vigencia de la presente Concurso. Dicha autorización se otorga en forma gratuita, sin obligación de compensación alguna, y para todo el territorio de la República Argentina. Los nombres, DNI y/o las fotos de los Participantes podrán ser utilizados y/o publicados en Internet y/o en diarios y/o en cualquier otro medio donde el Organizador lo considere conveniente o necesario. En aquellas jurisdicciones en las que la previsión de este punto no fuere exigible, el Organizador podrá condicionar la entrega de los Premios a que sus respectivos ganadores suscriban una autorización para la utilización de su nombre, DNI y/o fotos con la misma extensión de lo previsto en este punto.</p>
            <p>12. Cualquier controversia que se produzca con motivo de la validez, interpretación y aplicación del Concurso, será resuelta por los tribunales ordinarios en la Provincia de Buenos Aires, República Argentina. Para todo lo que no se mencione expresamente en estas Bases, rigen las normas establecidas en el Código Civil referente al tema. Este Sorteo se realiza bajo la modalidad “SIN OBLIGACION DE COMPRA”.</p>
        </div>
    )
}

export default Bases